HS-150

diff --git a/.github/workflows/jira-publish.yml b/.github/workflows/jira-publish.yml
--- a/.github/workflows/jira-publish.yml
+++ b/.github/workflows/jira-publish.yml
@@ -1,26 +1,37 @@
 name: Jira Ticket Validation
 
 on:
-  pull_request
+  pull_request:
 
 jobs:
-  branchName:
-    name: Branch Validation
+  ticketValidation:
+    name: Ticket Validation
     runs-on: ubuntu-latest
+
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - uses: octokit/request-action@v2.x
-        id: get_pr_commits
-        with:
-          route: GET /repos/Hotel-Simulator/Hotel-Simulator/pulls/{pull_number}/commits
-          pull_number: ${{ github.event.pull_request.number }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Validate Jira ticket numbers
+        run: |
+          # Regular expression to match Jira ticket number format "HS-21"
+          JIRA_TICKET_REGEX="HS-[0-9]+"
 
-      - name: Validate JIRA branch name and PR/commit consistency
-        uses: worksome/jira-branch-name-validator-action@v2.0.0
-        with:
-          branch-name: ${{ github.event.pull_request.head.ref }}
-          pr-title: ${{ github.event.pull_request.title }}
-          commits: ${{ steps.get_pr_commits.outputs.data }}
-          prefix: HS
+          # Get the branch name
+          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
+
+          # Get the PR title
+          PR_TITLE="${{ github.event.pull_request.title }}"
+
+          # Get the commit messages
+          COMMIT_MESSAGES=$(git log --pretty=format:%s ${{ github.event.before }}..${{ github.sha }})
+
+          # Check if the Jira ticket number is present in the branch name, PR title, and commit messages
+          if echo "$BRANCH_NAME" | grep -q -E "$JIRA_TICKET_REGEX" &&
+             echo "$PR_TITLE" | grep -q -E "$JIRA_TICKET_REGEX" &&
+             echo "$COMMIT_MESSAGES" | grep -q -E "$JIRA_TICKET_REGEX"; then
+            echo "All commit messages, PR title, and branch name have a Jira ticket number."
+          else
+            echo "Jira ticket number missing in one or more: commit messages, PR title, or branch name."
+            exit 1
+          fi
